// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qgmwavsckdeztmlhmtre.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFnbXdhdnNja2RlenRtbGhtdHJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyOTI4NTksImV4cCI6MjA2OTg2ODg1OX0.Tvkyhu7vYAb8sfr874Aq24pYSuOINnQE4omdwkfYXhY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});